description: "An easily-extensible web server framework in Dart."
homepage: "https://github.com/angel-dart/angel"
name: "dart_jsdaddy_school"
publish_to: "none"
dependencies:
  angel_auth: "^1.1.0"
  angel_configuration: "^1.1.0"
  angel_cors: "^1.0.0"
  angel_framework: "^1.1.0"
  angel_mustache: "^1.1.0"
  angel_serialize: "^2.0.0"
  angel_static: "^1.3.0"
  angel_validate: "^1.0.0"
  angel_mongo: "^1.0.0"
  mailer: "^1.1.4"
  redux: "^3.0.0"
  redux_epics: "^0.9.0"
  http: "^0.11.3+16"
  mustache: "^1.0.0"
dev_dependencies:
  angel_hot: "^1.1.0-alpha"
  angel_serialize_generator: "^2.0.0"
  angel_test: "^1.1.0"
  build_runner: "^0.7.0"
  console: "^2.2.4"
  grinder: "^0.8.0"
  test: "^0.12.13"
  sass: "^1.2.1"
environment:
  sdk: ">=2.0.0-dev <2.0.0"
