name: Deploy Landing

on:
  push:
    branches:
      - master

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Deploy
     uses: appleboy/ssh-action@master
     env:
       USERNAME: ${{ secrets.my_username }}
       HOST: ${{ secrets.my_host }}
       PASSWORD: ${{ secrets.PASSWORD }}
       SCRIPT: |
          whoami
          cd landing
          git pull origin master
          npm run deploy
       script_stop: true
