name: Deploy Landing

on: [push]

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Deploy
     uses: appleboy/ssh-action@master
     env:
       USERNAME: ${{ secrets.my_username }}
       HOST: ${{ secrets.my_host }}
       PASSWORD: ${{ secrets.PASSWORD }}
       SCRIPT: |
          whoami
          nvm use 10.16.3
          nvm install-latest-npm
          cd landing
          git pull origin master
          npm run deploy
       script_stop: true
