name: Deploy Landing

on:
  push:
    branches:
      - master

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Deploy
     uses: appleboy/ssh-action@master
     env:
       USERNAME: ${{ secrets.my_username }}
       HOST: ${{ secrets.my_host }}
       PASSWORD: ${{ secrets.PASSWORD }}
       SCRIPT: |
          whoami
          cd landing
          git pull origin master
          docker build -t jsdaddy/landing .
          docker stop landing-container
          docker rm landing-container
          docker run -p 3000:3000 --name landing-container -d jsdaddy/landing
       script_stop: true
